### ISSUE TITLE
How to declare "definitions"?

### ISSUE THREAD

**Issue by amitu** [NoRedInk/json-elm-schema#12]
Consider this [example](http://json-schema.org/example2.html).

They have definitions:

```js
{
    ...
    "definitions": {
        "diskDevice": {
            "properties": {
                "device": {
                    "type": "string",
                    "pattern": "^/dev/[^/]+(/[^/]+)*$"
                }
            },
        },
    }
}
```

How do I create these definitions?

**Comment by amitu** [comment]
If I have to create this, I think I will have to modify BaseSchema to:

```elm
type alias BaseSchema extras =
    { extras
        | title : Maybe String
        , description : Maybe String
        , definitions: Maybe (Dict String Schema)
    }
```

The [spec mentions `definitions` as key in many examples](http://json-schema.org/latest/json-schema-core.html#rfc.section.9.2), but not sure if its convention, or part of standard.  From the specs it appears I can say `"$ref": "#/foo/diskDevice"` as well, and my schema must contain other schemas under the key `foo`. 

Also to complicate things further, spec doesn't even say that all definitions have to be stored in precisely one key, they can nested inside every `properties` of some object etc (as long as reference resolves, it should pick up).  

I just verified with python port of json-schema, and it allows (and successfully):

```py
{
  "foo": {
    "bar": {
      "person": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          }
       }
  }
}
```

Using `"$ref" = "#/foo/bar/person"`.

**Comment by amitu** [comment]
Another approach could be to modify the `cli`/`encodeSchemaProgram`, and try to create custom `Encode.Value` against my own some type e.g.:

```elm
type MySchema = 
    { definitions : Dict String Schema }
```

or 
```elm
type MySchema = 
    { foo : { bar : Dict String Schema } }
```

I can not figure out a type that will contain ObjectSchema on top, and will embed these extra record values.

Easiest thing feel like "just write some python script to create the final schema based on definitions stored in separate files" :-p.

**Comment by jwoudenberg** [comment]
Hey @amitu! Can I ask you what you want to use the definitions for? To me the definitions appear to basically be variables within the JSON schema language. In Elm you can use regular variables to split out parts of a schema you want to reuse.

```elm
schema : Schema
schema =
    object
        [ properties
            [ required "sub" subschema ]
        ]


subschema : Schema
subschema =
    integer []
```

An extra advantage of this approach is that you will never end up with a ref pointing to a locaion in the schema that does not exist. Would that be enough for your use case?

If you're worried about the size if your schema becoming to big, you can wrap your subschema in a `lazy` call.

```elm
subschema : Schema
subschema =
    lazy <| \_ -> integer []
```

Encoding such a schema will result in the subschema only appearing once in the encoded json.

**Comment by amitu** [comment]
Hey @jwoudenberg, thanks for the tip. I will try this and let you know how it goes.

**Comment by amitu** [comment]
It works for me. Thanks.
