### ISSUE TITLE
enum on boolean

### ISSUE THREAD

**Issue by amitu** [NoRedInk/json-elm-schema#14]
Currently I can specify enums on string/integer etc. But I need it on boolean too.

What I am trying to do is to specify my API's success and error schemas. In both cases my api contains a property/key "success" at top level. I have two separate schema documents to represent success and error cases. Both say "success" can be boolean. But I want more, I want to go and say that success schema can have only `success=True`. 

I think allowing enum should solve this. Does it make sense or I am suffering from OCD?

**Comment by jwoudenberg** [comment]
Makes sense to me! I'm not sure I'll get around to this soon, would be happy to accept a pull request for such a feature though!

**Comment by amitu** [comment]
```
➜  tests git:(master) elm-make Main.elm
Success! Compiled 1 module.
Successfully generated index.html
➜  tests git:(master) elm-make -v 
elm-make 0.18 (Elm Platform 0.18.0)
```
