### ISSUE TITLE
examples using `List Json.Encode.Value`?

### ISSUE THREAD

**Issue by amitu** [NoRedInk/json-elm-schema#23]
I need examples now. I am auto generating schema docs now, and it would be good to have examples in there.

I see that this project doesn't support it yet, and I thought how would I implement it. Being in the hurry I am, I thought of `List Json.Encode.Value` as value of examples:

```elm
action : Schema
action =
    object
        [ properties
            [ required "name" <| string []
            , required "id" <| string []
            , required "fields" <| array [ items task_field ]
            ]
        , maxProperties 3
        , examples 
            [ JE.object 
                [ ("name", JE.string "Tom")
                , ("id", JE.int "42")
                ]
            ]
        ]
```

Problem with this approach, as can be seen from the example, the field `fields` is missing. There is no validation on the example. Which happens to be in accordance with the specs.

Does it make sense? Should I try to create a pull request?

**Comment by jwoudenberg** [comment]
I don't really see a way around this. Perhaps validation of the examples could be another example of a place where a runtime validation of a schema would be helpful.

PR is welcome!

**Comment by amitu** [comment]
Update:

@jatinderjit has done some initial work on this, track [this branch](https://github.com/jatinderjit/json-elm-schema/tree/examples) if interested. 

Examples are coming in JSON, but tests are failing. He is working on it right now, we may have something next week.

**Comment by jwoudenberg** [comment]
Awesome! Thanks for the update!
