### ISSUE TITLE
decoder

### ISSUE THREAD

**Issue by norpan** [NoRedInk/json-elm-schema#4]
I have code that decodes a json-schema to an Elm datatype that is similar to yours.
Decoding would be the first step of #3 so I'm wondering if you're working on a decoder, otherwise I could try to adapt the code I have to your datatype and send a PR.

It makes sense to use the same Elm data structure for decoding and encoding.

**Comment by jwoudenberg** [comment]
I'm not working on a decoder at the moment, so a PR would be awesome! Let me know if you have any requirements with regards to the datatypes, which I know don't yet cover the full spec.

**Comment by norpan** [comment]
I've made a decoder for the data type, but the problem is that not many JSON Schema documents will parse with it.

While it's very nice to be able to generate "type-safe" JSON Schemas, I'm afraid that it's not a very good target for a JSON schema decoder.

I can send a PR for the decoder if you like. For now I'm going to continue to work on another representation of JSON Schema in my project.

**Comment by jwoudenberg** [comment]
Thanks for looking into this! I can see that elm-json-scema is more strict than most schema's are. I wonder if we could we add something similar to [Elm-Css's property](http://package.elm-lang.org/packages/rtfeldman/elm-css/8.2.0/Css#property), as a catch-all for any json-schema property not currently supported by the static schema? In the case of JSON schema's, it might contain arbitrary JSON `Value`s.

**Comment by norpan** [comment]
It's not just that we need a catch-all, it's also that you can combine `oneOf` with `type: "string"` and things like that.

For a catch-all you can just use a `Schema = ... | Unknown BaseSchema` and put a `unknown: Dict String Value` in the BaseSchema. That way you can keep all the values regardless of which "type-safe" schema you decode to (you probably want to filter out the known values from the Dict in the decoder).

**Comment by jwoudenberg** [comment]
That's a nice solution! I think just adding an `Unknown Value` constructor to the base schema is enough as a first step: if any schema contains properties not covered by the representation, that entire schema can become be wrapped in `Unknown`. This would also take care of your `oneOf` with `type: "string"` example.

A smarter decoding process might even parse a JSON schema to an equivalent standardized form. For instance, in your `oneOf` example, it can take the `type` property of the `oneOf` root and put it on all the children. I'm not sure that's actually the best standardized form in this instance, but it serves for the example.

That said, I can imagine having part of the schema in an opague `Value` type would not suit your particular use case, so not trying to push any ideas on you. I appreciate the discussion. And if you have a link to your decoder projects I'd love to take a look!

**Comment by norpan** [comment]
Well, the point is that this is a valid schema:
```json
{ "type": "string"
, "oneOf": [{"type": "uri"}, {"type":"email"}]
}
```
So, would this be a `String` or a `OneOf` schema?

**Comment by norpan** [comment]
Sorry, deleted my comment.
My point is that you only allow "type-safe" schemas, but schemas might not be type safe.

What to make of this?
```
{ "oneOf":
  [ { "type": "string" }
  , { "type": "number" }
  ]
}
```

Will validate `"aString"` and `1`. So a "type-safe" type will not be able to represent all valid or useful schemas.

**Comment by jwoudenberg** [comment]
That schema is perfectly fine as far as elm-json-schema is concerned!

The lib doesn't want to force you to write 'type-safe' schemas, just correct ones. To give you an example of an incorrect schema:

```json
{
  "type": "object",
  "minLength": 3
}
```

An object cannot have a `minLength`.


The is similar to elm-css. The library seeks to allow you to write any valid css while helping you prevent mistakes..

**Comment by norpan** [comment]
Aha, yes you are right, maybe I can use it after all :)
Maybe it's just that a number of options are lacking. I'll have a new look at it, and I'll PR my current decoder. I'll write some tests though.

**Comment by jwoudenberg** [comment]
Cool! Let me know if I can be of any help!
